ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 224
    HEIGHT: 224
    HFOV: 90
    TYPE: HabitatSimRGBSensor
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
    TYPE: HabitatSimDepthSensor
  TURN_ANGLE: 15
  TILT_ANGLE: 15
  ACTION_SPACE_CONFIG: v0
TASK:
  TYPE: VLN-v0
  SUCCESS_DISTANCE: 3.0
  SENSORS: ['INSTRUCTION_SENSOR', 'BERT_INSTRUCTION_SENSOR', 'SHORTEST_PATH_SENSOR', 'VLN_ORACLE_PROGRESS_SENSOR', 'WAYPOINT_SENSOR']
  INSTRUCTION_SENSOR_UUID: instruction
  
  # üî• ËøôÈáåÊòØÂÖ≥ÈîÆÔºÅÂú®Âü∫Á°ÄÈÖçÁΩÆÈáåÁõ¥Êé•ÂÆö‰πâËøô13‰∏™Âä®‰Ωú
  POSSIBLE_ACTIONS: [
    'CANDIDATE_MOVE_0', 'CANDIDATE_MOVE_1', 'CANDIDATE_MOVE_2', 'CANDIDATE_MOVE_3',
    'CANDIDATE_MOVE_4', 'CANDIDATE_MOVE_5', 'CANDIDATE_MOVE_6', 'CANDIDATE_MOVE_7',
    'CANDIDATE_MOVE_8', 'CANDIDATE_MOVE_9', 'CANDIDATE_MOVE_10', 'CANDIDATE_MOVE_11',
    'STOP'
  ]
  ACTIONS:
    STOP:
      TYPE: StopAction
    CANDIDATE_MOVE_0:
      TYPE: CANDIDATE_MOVE_0
    CANDIDATE_MOVE_1:
      TYPE: CANDIDATE_MOVE_1
    CANDIDATE_MOVE_2:
      TYPE: CANDIDATE_MOVE_2
    CANDIDATE_MOVE_3:
      TYPE: CANDIDATE_MOVE_3
    CANDIDATE_MOVE_4:
      TYPE: CANDIDATE_MOVE_4
    CANDIDATE_MOVE_5:
      TYPE: CANDIDATE_MOVE_5
    CANDIDATE_MOVE_6:
      TYPE: CANDIDATE_MOVE_6
    CANDIDATE_MOVE_7:
      TYPE: CANDIDATE_MOVE_7
    CANDIDATE_MOVE_8:
      TYPE: CANDIDATE_MOVE_8
    CANDIDATE_MOVE_9:
      TYPE: CANDIDATE_MOVE_9
    CANDIDATE_MOVE_10:
      TYPE: CANDIDATE_MOVE_10
    CANDIDATE_MOVE_11:
      TYPE: CANDIDATE_MOVE_11

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'NDTW', 'PATH_LENGTH', 'ORACLE_SUCCESS', 'STEPS_TAKEN']
  SPL:
    SUCCESS_DISTANCE: 3.0
  NDTW:
    SUCCESS_DISTANCE: 3.0
    GT_PATH: data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}_gt.json.gz
  SUCCESS:
    SUCCESS_DISTANCE: 3.0
  DISTANCE_TO_GOAL:
    DISTANCE_TO: POINT
  ORACLE_SUCCESS:
    SUCCESS_DISTANCE: 3.0
  WAYPOINT_SENSOR:
    TYPE: WaypointSensor
    NUM_CANDIDATES: 12
    MAX_DISTANCE: 2.5
    MIN_DISTANCE: 0.5
  BERT_INSTRUCTION_SENSOR:
    TYPE: BertInstructionSensor
    MAX_LENGTH: 200

DATASET:
  TYPE: VLN-CE-v1
  SPLIT: train
  DATA_PATH: data/datasets/R2R_VLNCE_v1-3_preprocessed/{split}/{split}.json.gz
  SCENES_DIR: data/scene_datasets/