name: vln-ce
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2025.12.2=h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.5=h7934f7d_0
  - numpy-base=1.23.5=py38h060ed82_1
  - openssl=3.0.17=h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==0.21.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - altair==5.4.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.5.2
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.14.3
      - bitsandbytes==0.41.0
      - braceexpand==0.1.7
      - certifi==2026.1.4
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==1.6.0
      - cmake==4.2.1
      - contourpy==1.1.1
      - cryptography==46.0.4
      - cycler==0.12.1
      - decorator==4.4.2
      - decord==0.6.0
      - distlib==0.4.0
      - dtw==1.4.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - exceptiongroup==1.3.1
      - fairscale==0.4.0
      - fastapi==0.124.4
      - fastdtw==0.3.4
      - ffmpy==0.5.0
      - filelock==3.16.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - future==1.0.0
      - gdown==5.2.1
      - google-auth==2.48.0
      - google-auth-oauthlib==1.0.0
      - gradio==3.35.2
      - gradio-client==0.2.9
      - grpcio==1.70.0
      - gym==0.17.3
      - gym-notices==0.1.0
      - h11==0.16.0
      - habitat-sim==0.1.7
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - identify==2.6.1
      - idna==3.11
      - ifcfg==0.24
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - linkify-it-py==2.0.3
      - lit==18.1.8
      - llvmlite==0.41.1
      - lmdb==1.4.1
      - markdown==3.7
      - markdown-it-py==2.2.0
      - markdown2==2.5.1
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.0.0
      - msgpack-numpy==0.4.8
      - multidict==6.1.0
      - narwhals==1.42.1
      - networkx==3.1
      - nodeenv==1.10.0
      - numba==0.58.1
      - numpy==1.21.6
      - numpy-quaternion==2023.0.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - objectio==0.2.29
      - opencv-python==4.13.0.90
      - orjson==3.10.15
      - packaging==26.0
      - pandas==2.0.3
      - peft==0.4.0
      - pillow==6.2.2
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - pre-commit==3.5.0
      - proglog==0.1.12
      - propcache==0.2.0
      - protobuf==3.20.3
      - psutil==7.2.1
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyglet==1.5.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rich==14.3.1
      - rpds-py==0.20.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - simplejson==3.20.2
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - starlette==0.44.0
      - svgwrite==1.4.3
      - sympy==1.13.3
      - tb-nightly==2.14.0a20230808
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - timm==0.6.13
      - tokenizers==0.13.3
      - torch==2.0.1
      - torchvision==0.2.2.post3
      - tqdm==4.67.1
      - transformers==4.31.0
      - triton==2.0.0
      - typer==0.21.1
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - uc-micro-py==1.0.3
      - urllib3==2.2.3
      - uvicorn==0.33.0
      - virtualenv==20.36.1
      - wavedrom==2.0.3.post3
      - webdataset==0.1.40
      - websockets==13.1
      - werkzeug==3.0.6
      - yacs==0.1.8
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/ShiKaituo/anaconda3/envs/vln-ce
